### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by viraatdas** [viraatdas/Video-Resolution-Enhancer#6]

**Comment by OneProblemAtATime** [comment]
Well, it isn't amazing, but I did get a basic version working that will help give a bit of user feedback. I have a pull request for this feature addition. I won't make another executable release until I have a few more features working though.

**Comment by viraatdas** [comment]
Closing this for now because PR is merged - thanks a lot for working on this. 

ttps://github.com/viraatdas/video-super-resolution/pull/10

**Comment by viraatdas** [comment]
@OneProblemAtATime  Also btw it would be great if you could email me at viraat.laldas@gmail.com

Want to chat about some potential features and ideas with you.
