### ISSUE TITLE
Binary release from fork is not available on the main branch

### ISSUE THREAD

**Issue by OneProblemAtATime** [viraatdas/Video-Resolution-Enhancer#9]
I just wanted to put this here so that the binary can be added to the main repo. There is still some modifications to be done, but the V0 release is fully working. I do not know how to transfer the release over though.

Here is the link to the releases page of my fork: https://github.com/OneProblemAtATime/video-super-resolution/releases/tag/V0-alpha

**Comment by viraatdas** [comment]
Thanks for following up on this. Went ahead and created a new tag with the release. I'll close this. Feel free to reopen it if I missed something.
